import Menu from "@/components/layout/Menu";
import Providers from "./providers";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Menu />
        <main>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
